server:
  port: 8082

spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  rabbitmq:
    host: rabbitmq
    port: 5672

routing-key:
  product: product_key
  currency: currency_key
  price: price_key

queue:
  product: product_queue
  currency: currency_queue
  price: price_queue

xchange:
  name: exchange_rpc

keycloak:
  realm: pokemon
  auth-server-url: http://localhost:8080/auth
  resource: spring-app
  bearer-only: true
